export const events = [
    {id: 1, image: '/src/assets/images/Andreana Cekic.jpg', title: 'Maja Berović', supportedByDj: 'Infinity', date: '13.12.2024', entry: 20, isEventSupportedByDj: true},
    {id: 2, image: '/src/assets/images/Djani.jpg', title: 'Darko Lazić', date: '14.12.2024'},
    {id: 3, image: '/src/assets/images/Edita & Cvija.jpg', title: 'Milorad Mandić', supportedByDj: 'Dex', date: '15.12.2024', isEventSupportedByDj: true},
    {id: 4, image: '/src/assets/images/Ladies night.jpg', title: 'Nataša Bekvalac', date: '16.12.2024', entry: 25},
    {id: 5, image: '/src/assets/images/Barbara Bobak.jpg', title: 'Aco Pejović', date: '18.12.2024'},
    {id: 6, image: '/src/assets/images/Breskvica.jpg', title: 'Aleksandra Prijović', supportedByDj: 'Alex', date: '13.12.2024', entry: 15, isEventSupportedByDj: true},
    {id: 7, image: '/src/assets/images/Djani.jpg', title: 'Mile Kitić', date: '14.12.2024', entry: 10},
    {id: 8, image: '/src/assets/images/Edita & Cvija.jpg', title: 'Dara Bubamara', date: '15.12.2024'},
    {id: 9, image: '/src/assets/images/Ladies night.jpg', title: 'Relja Popović', date: '16.12.2024'},
    {id: 10, image: '/src/assets/images/Rasta.jpg', title: 'Seka Aleksić', date: '17.12.2024'},
    {id: 11, image: '/src/assets/images/Barbara Bobak.jpg', title: 'Teodora Džehverović', date: '18.12.2024'},
    {id: 12, image: '/src/assets/images/Breskvica.jpg', title: 'Ceca Ražnatović', date: '13.12.2024'},
    {id: 13, image: '/src/assets/images/Djani.jpg', title: 'Saša Matić', date: '14.12.2024'},
    {id: 14, image: '/src/assets/images/Edita & Cvija.jpg', title: 'Lepa Brena', date: '15.12.2024'},
    {id: 15, image: '/src/assets/images/Ladies night.jpg', title: 'Zdravko Čolić', date: '16.12.2024'},
    {id: 16, image: '/src/assets/images/Rasta.jpg', title: 'Marija Šerifović', date: '17.12.2024'},
    {id: 17, image: '/src/assets/images/Barbara Bobak.jpg', title: 'Bojan Tomović', date: '18.12.2024'},
    {id: 18, image: '/src/assets/images/Andreana Cekic.jpg', title: 'Ana Nikolić', date: '17.12.2024'},
    {id: 19, image: '/src/assets/images/Andreana Cekic.jpg', title: 'Sanja Vučić', date: '13.12.2024'},
    {id: 20, image: '/src/assets/images/Djani.jpg', title: 'Dejan Matić', date: '14.12.2024'},
    {id: 21, image: '/src/assets/images/Edita & Cvija.jpg', title: 'Jala Brat', date: '15.12.2024'},
    {id: 22, image: '/src/assets/images/Ladies night.jpg', title: 'Maya Berović', date: '16.12.2024'},
    {id: 23, image: '/src/assets/images/Barbara Bobak.jpg', title: 'Ana Bekuta', date: '18.12.2024'},
    {id: 24, image: '/src/assets/images/Breskvica.jpg', title: 'Dragana Mirković', date: '13.12.2024'},
    {id: 25, image: '/src/assets/images/Djani.jpg', title: 'MC Stojan', date: '14.12.2024'},
    {id: 26, image: '/src/assets/images/Edita & Cvija.jpg', title: 'Jelena Karleuša', date: '15.12.2024'},
    {id: 27, image: '/src/assets/images/Ladies night.jpg', title: 'Rasta', date: '16.12.2024'},
    {id: 28, image: '/src/assets/images/Rasta.jpg', title: 'Vuk Mob', date: '17.12.2024'},
    {id: 29, image: '/src/assets/images/Barbara Bobak.jpg', title: 'Goca Tržan', date: '18.12.2024'},
    {id: 30, image: '/src/assets/images/Breskvica.jpg', title: 'Milan Stanković', date: '13.12.2024'},
    {id: 31, image: '/src/assets/images/Djani.jpg', title: 'Indira Radić', date: '14.12.2024'},
    {id: 32, image: '/src/assets/images/Edita & Cvija.jpg', title: 'Stefan Cvijović Cvija', date: '15.12.2024'},
    {id: 33, image: '/src/assets/images/Ladies night.jpg', title: 'Mimi Mercedez', date: '16.12.2024'},
    {id: 34, image: '/src/assets/images/Rasta.jpg', title: 'Bane Mojićević', date: '17.12.2024'},
    {id: 35, image: '/src/assets/images/Barbara Bobak.jpg', title: 'Nikolina Kovač', date: '18.12.2024'},
    {id: 36, image: '/src/assets/images/Andreana Cekic.jpg', title: 'Đani', date: '17.12.2024'}
];